language: python
notifications:
  email:
    recipients:
      - qingyuc@alumni.cmu.edu
    on_success: never
    on_failure: always
jobs:
  include:
    - name: "Python on Linux"
      python:
        - "3.8"
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
        - pip3 install bs4
        - pip3 install mapboxgl
        - pip3 install IPython
        - pip3 install pytest-flake8
        #- pip3 install -r req.txt
        - pip3 install -r requirements.txt

      
      # command to run tests
      install:
        - pip install . 
      script:
        - python3 -m pytest yelp_reviews/tests/*
        - pytest --flake8