language: python
notifications:
  email:
    recipients:
      - qingyuc@alumni.cmu.edu
    on_success: never
    on_failure: always
jobs:
  include:
    - name: "Python on Linux"
      python:
        - "3.6"      # current default Python on Travis CI
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.9-dev"  # 3.9 development branch
        - "nightly"  # nightly build
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
        #pip3 install bs4
        #- pip3 install lxml
        #- pip3 install pytest-flake8
        #- pip3 install --user -r requirements.txt
      
      # command to run tests
      install:
        - pip install . 
      script:
        - python3 -m pytest yelp_reviews/code/tests/*
        #- pytest --flake8
